-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -o "D:/CO/P1/P1.Q4/gray_tb_isim_beh.exe" -prj "D:/CO/P1/P1.Q4/gray_tb_beh.prj" "work.gray_tb" "work.glbl" 
